# Generated by Django 4.0.7 on 2022-08-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pet_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
