# Generated by Django 4.0.7 on 2022-08-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_pet_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='post',
            name='pet_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
